### PR TITLE
Fixes Openai realtime implementation, fixing tool usage in particular.

### PR DESCRIPTION
**Pull request by josancamon19**
Fixes for using openai realtime api. Tool calling is not working in current library version, this imp fixes it, additionally, receiving user role messages was triggering an exception.

### CODE REVIEW

**Comment by davidmigloz** [comment]
Released in https://pub.dev/packages/openai_realtime_dart/changelog#0012

**Comment by caleb654** [comment]
I'm on the latest version and tool usage doesn't seem to be working. I tried adding a basic tool in both ways shown in the docs but the model does not know that the tool exists.

**Comment by davidmigloz** [comment]
Hey @caleb654,

Can you provide a test that reproduces the issue you're experiencing?

I've just rerun this test that tests tool use, and it's still passing:
https://github.com/davidmigloz/langchain_dart/blob/194534c8567fd19d6c183ca37aafa5bbfc985837/packages/openai_realtime_dart/test/client_test.dart#L88-L197

**Comment by caleb654** [comment]
Sorry seems to be working now. I think my implementation was just messed up.

**Pull request merged**
